##
# MVdWPlaceholderAPI
#
# @copyright Maxim Van de Wynckel
##

name: MVdWPlaceholderAPI
version: 2.0.11
description: Placeholder API for MVdW Software plugins
author: Maximvdw
website: http://www.mvdw-software.com/
main: be.maximvdw.placeholderapi.PlaceholderAPI